#!/usr/bin/env bash
# huihui-qwen3-coder-30b-a3b-instruct-abliterated-gguf — llama.cpp single-node controller (GGUF)
# Model:    mradermacher/Huihui-Qwen3-Coder-30B-A3B-Instruct-abliterated-GGUF @ d7da518983e85529d7e7de7c9ef3901bcf9d8f51
# File:     Huihui-Qwen3-Coder-30B-A3B-Instruct-abliterated.Q6_K.gguf
# Target:   this-machine | Generated by LMDS 0.3.0 (rule-based)
# Standard: dgx-spark-controllers v3.0.0 controller contract
set -Eeuo pipefail

# ============================ CONFIG (แก้ได้) ============================
SCRIPT_VERSION="${SCRIPT_VERSION:-0.3.0}"
MODEL_LABEL="${MODEL_LABEL:-mradermacher/Huihui-Qwen3-Coder-30B-A3B-Instruct-abliterated-GGUF}"
RUNTIME_LABEL="${RUNTIME_LABEL:-llama.cpp (native build)}"
MODEL_FEATURES="tools · coding"
MODEL_ID="mradermacher/Huihui-Qwen3-Coder-30B-A3B-Instruct-abliterated-GGUF"
MODEL_REVISION="d7da518983e85529d7e7de7c9ef3901bcf9d8f51"
# ชื่อโมเดลที่ API เสิร์ฟออกไป — ตั้งเองได้ผ่าน env เหมือน knob อื่น ๆ
# ลูกค้าที่ย้ายมาจากระบบเดิมมักต้องใช้ชื่อเดิมเป๊ะ ไม่งั้น client ทุกตัวต้องแก้ตาม
SERVED_MODEL_NAME="${SERVED_MODEL_NAME:-huihui-qwen3-coder-30b-a3b-instruct-abliterated-gguf}"

# runtime mode: docker (RTX x86_64, image ทางการ) | native (DGX Spark ARM64 — build จาก source)
RUNTIME_MODE="${RUNTIME_MODE:-native}"
# image เปลี่ยนผ่าน env ได้เหมือน knob อื่น ๆ — bundle ที่ image ใช้ไม่ได้ (tag ผิด/ถูกถอน)
# จะได้แก้ได้โดยไม่ต้อง deploy ใหม่ทั้งชุด · stacked ทำแบบนี้อยู่แล้ว single ตกไป
# runtime ของ bundle นี้ — ตรึงที่ digest ไม่ใช่ tag
#
# tag เคลื่อนที่ได้: `:latest` วันนี้กับเดือนหน้าเป็นคนละ image · bundle ที่ทดสอบ
# ผ่านแล้วจึงกลายเป็นคนละ runtime ได้โดยไม่มีอะไรในไฟล์นี้เปลี่ยนเลย ซึ่งเป็นอาการ
# ที่ไล่หาสาเหตุยากที่สุด เพราะ "ไม่ได้แก้อะไรสักหน่อย"
#
# tag ที่ digest นี้มาจาก ณ วันที่ generate: ghcr.io/ggml-org/llama.cpp:server-cuda
# อยากใช้ตัวอื่นก็ override ได้ตามเดิม: LLAMACPP_IMAGE=<image> ./controller start
LLAMACPP_IMAGE="${LLAMACPP_IMAGE:-ghcr.io/ggml-org/llama.cpp@sha256:b5e13ddfaa3df76d239ee038075960a46f595201808728fd70bbf2c8b38f6530}"
LLAMA_CPP_REPO="${LLAMA_CPP_REPO:-https://github.com/ggml-org/llama.cpp.git}"
LLAMA_CPP_REF="${LLAMA_CPP_REF:-master}"
# build ที่โมเดลนี้ผูกไว้ — ไม่ใช่ build กลางของเครื่อง เว้นแต่ไม่ได้ pin ไว้
LLAMA_CPP_DIR="${LLAMA_CPP_DIR:-${HOME}/src/llama.cpp}"
LLAMA_SERVER="${LLAMA_SERVER:-${LLAMA_CPP_DIR}/build/bin/llama-server}"
CUDA_ARCHITECTURES="${CUDA_ARCHITECTURES:-121a-real}"
CONTAINER_NAME="${CONTAINER_NAME:-lmds-huihui-qwen3-coder-30b-a3b-instruct-abliterated-gguf}"

# ── ค่าที่บันทึกไว้กับ bundle นี้ (เขียนโดยหน้าเว็บ / `lmds set`) ──
# อ่านก่อน default ทั้งหมดข้างล่าง และทุกบรรทัดในไฟล์เป็นรูป ${VAR:-value} ลำดับ
# ความสำคัญจึงเป็น: flag บรรทัดคำสั่ง > env จากภายนอก > ไฟล์นี้ > ค่าของ bundle
#
# มีไฟล์นี้เพราะค่าที่ตั้งบนหน้าเว็บเคยอยู่แค่ในเบราว์เซอร์: systemd ตอน autostart
# และปุ่ม test-* เรียก controller เปล่า ๆ ทุกตัวจึงตกไปใช้ default — พอ reboot
# โมเดลทุกตัวบนเครื่องเดียวกันก็ไปชนกันที่ port เดียว
BUNDLE_ENV="${BUNDLE_ENV:-$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/bundle.env}"
if [[ -f "$BUNDLE_ENV" ]]; then
  set -a; . "$BUNDLE_ENV"; set +a
fi

MODEL_DIR="${MODEL_DIR:-${HOME}/models/huihui-qwen3-coder-30b-a3b-instruct-abliterated-gguf}"
RUN_DIR="${RUN_DIR:-${HOME}/.lmds/run/huihui-qwen3-coder-30b-a3b-instruct-abliterated-gguf}"
PID_FILE="${RUN_DIR}/server.pid"
LOG_FILE="${RUN_DIR}/server.log"
RUNTIME_LOCK="${RUN_DIR}/runtime.lock"

# ไฟล์โมเดล (split GGUF จะมีหลาย part — ต้องครบทุกไฟล์)
MODEL_FILES=(
  "Huihui-Qwen3-Coder-30B-A3B-Instruct-abliterated.Q6_K.gguf"
)
MODEL_URLS=(
  "https://huggingface.co/mradermacher/Huihui-Qwen3-Coder-30B-A3B-Instruct-abliterated-GGUF/resolve/d7da518983e85529d7e7de7c9ef3901bcf9d8f51/Huihui-Qwen3-Coder-30B-A3B-Instruct-abliterated.Q6_K.gguf"
)
EXPECTED_SIZES=(
  "25092535488"
)
EXPECTED_SHAS=(
  ""
)
MODEL_FILE="${MODEL_FILES[0]}"


CTX_SIZE="${CTX_SIZE:-262144}"
API_HOST="${API_HOST:-0.0.0.0}"
API_PORT="${API_PORT:-8000}"
API_KEY="${API_KEY:-}"
ADVERTISE_IP="${ADVERTISE_IP:-}"
ADVERTISE_INTERFACE="${ADVERTISE_INTERFACE:-}"
ROUTE_PROBE_IP="${ROUTE_PROBE_IP:-1.1.1.1}"

N_GPU_LAYERS="${N_GPU_LAYERS:-999}"
PARALLEL_SEQS="${PARALLEL_SEQS:-1}"
CLIENT_OUTPUT="${CLIENT_OUTPUT:-5120}"
CLIENT_INPUT="${CLIENT_INPUT:-auto}"
TEMPLATE_OVERHEAD_TOKENS="2048"
HEALTH_TIMEOUT="${HEALTH_TIMEOUT:-600}"
# ========================================================================

die() { echo "ERROR: $*" >&2; exit 1; }

# พอร์ตเดียวกันรับได้ทีละเซิร์ฟเวอร์ และทุก bundle ตั้งต้นที่พอร์ตเดียวกัน — ถ้าโมเดลอื่น
# ยึดพอร์ตนี้อยู่ ชุดทดสอบจะยิงไปโดนตัวนั้นแล้ว "ผ่าน" ทั้งที่ทดสอบคนละโมเดล
# (เจอจริง: test-text ของ gemma-4-31b ได้คำตอบจาก Qwen3-Coder-30B ที่รันอยู่ก่อน)
assert_our_server() {
  local seen
  seen="$(curl -fsS -m 10 "http://127.0.0.1:${API_PORT}/v1/models" \
    ${API_KEY:+-H "Authorization: Bearer $API_KEY"} 2>/dev/null \
    | { command -v python3 >/dev/null 2>&1 && python3 -c '
import json, sys
try:
    data = json.load(sys.stdin)["data"]
except Exception:
    sys.exit(0)
print((data[0].get("id") or "").strip() if data else "")
' || cat; })" || return 0
  [ -n "$seen" ] || return 0                       # อ่านไม่ได้ = ไม่ฟันธง ปล่อยผ่าน
  [ "$seen" = "$SERVED_MODEL_NAME" ] && return 0
  die "พอร์ต ${API_PORT} ตอบมาเป็นโมเดล '${seen}' ไม่ใช่ '${SERVED_MODEL_NAME}'
     มีเซิร์ฟเวอร์อื่นยึดพอร์ตนี้อยู่ — ผลทดสอบที่ได้จะเป็นของโมเดลนั้น ไม่ใช่ตัวนี้
     แก้: หยุดตัวที่ชน หรือรันตัวนี้คนละพอร์ต  $0 restart --port 8001"
}
need() { command -v "$1" >/dev/null 2>&1 || die "missing dependency: $1"; }

validate_numbers() {
  [[ "$API_PORT" =~ ^[0-9]+$ ]] && (( API_PORT >= 1 && API_PORT <= 65535 )) ||
    die "invalid API_PORT: $API_PORT"
  [[ "$CTX_SIZE" =~ ^[0-9]+$ ]] && (( CTX_SIZE > 0 )) ||
    die "invalid context: $CTX_SIZE"
  [[ "$CLIENT_OUTPUT" =~ ^[0-9]+$ ]] && (( CLIENT_OUTPUT > 0 )) ||
    die "invalid CLIENT_OUTPUT: $CLIENT_OUTPUT"
}

detect_advertise_ip() {
  if [[ -n "$ADVERTISE_IP" ]]; then printf '%s' "$ADVERTISE_IP"; return; fi
  if [[ -n "$ADVERTISE_INTERFACE" ]]; then
    ip -4 -o addr show dev "$ADVERTISE_INTERFACE" scope global |
      awk 'NR == 1 { split($4, a, "/"); print a[1] }'
    return
  fi
  local route_src
  route_src="$(ip -4 route get "$ROUTE_PROBE_IP" 2>/dev/null |
    awk '{ for (i=1; i<=NF; i++) if ($i=="src") { print $(i+1); exit } }')"
  if [[ -n "$route_src" ]]; then printf '%s' "$route_src"; return; fi
  hostname -I 2>/dev/null | awk '{print $1}'
}

parse_options() {
  REMAINING_ARGS=()
  while (( $# )); do
    case "$1" in
      --context)        CTX_SIZE="$2"; shift 2 ;;
      --context=*)      CTX_SIZE="${1#*=}"; shift ;;
      --port)           API_PORT="$2"; shift 2 ;;
      --port=*)         API_PORT="${1#*=}"; shift ;;
      --bind)           API_HOST="$2"; shift 2 ;;
      --bind=*)         API_HOST="${1#*=}"; shift ;;
      --advertise-ip)   ADVERTISE_IP="$2"; shift 2 ;;
      --advertise-ip=*) ADVERTISE_IP="${1#*=}"; shift ;;
      --interface)      ADVERTISE_INTERFACE="$2"; shift 2 ;;
      --interface=*)    ADVERTISE_INTERFACE="${1#*=}"; shift ;;
      --client-input)   CLIENT_INPUT="$2"; shift 2 ;;
      --client-input=*) CLIENT_INPUT="${1#*=}"; shift ;;
      --client-output)  CLIENT_OUTPUT="$2"; shift 2 ;;
      --client-output=*) CLIENT_OUTPUT="${1#*=}"; shift ;;
      *) REMAINING_ARGS+=("$1"); shift ;;
    esac
  done
  validate_numbers
}

network_info() {
  echo "Bind:      ${API_HOST}:${API_PORT}"
  echo "Endpoint:  http://$(detect_advertise_ip):${API_PORT}/v1"
  echo "Model:     ${SERVED_MODEL_NAME} (${MODEL_FILE})"
  echo "Context:   ${CTX_SIZE}"
  echo "Runtime:   ${RUNTIME_MODE}"
}

download() {
  need curl
  mkdir -p "$MODEL_DIR"
  local i
  for i in "${!MODEL_FILES[@]}"; do
    echo "download [$(( i + 1 ))/${#MODEL_FILES[@]}]: ${MODEL_URLS[$i]}"
    fetch_one "${MODEL_URLS[$i]}" "${MODEL_DIR}/${MODEL_FILES[$i]}"
  done
  echo "download complete: ${MODEL_DIR} (${#MODEL_FILES[@]} ไฟล์)"
}

# ดึงหนึ่งไฟล์ · ใช้ aria2c ถ้ามี (เปิดหลาย connection พร้อมกัน) ไม่งั้นถอยไป curl
# ทำไม: CDN บางเจ้า (เจอจริงกับ bartowski) throttle ต่อ connection เหลือ ~150KB/s
# ทั้งที่เครื่องมีแบนด์วิดท์เหลือ — 63GB จะกลายเป็น 6 ชั่วโมงทั้งที่ควรเสร็จใน 20 นาที
# aria2c -x16 เปิด 16 ช่องขนานจึงเลี่ยง throttle ต่อ connection ได้ · ทั้งคู่ resume ได้
# (ไฟล์ที่โหลดค้างไว้ทำต่อ ไม่เริ่มใหม่) และ verify_files เช็ก size ต่อทุกครั้งอยู่แล้ว
fetch_one() {
  local url="$1" out="$2"
  if command -v aria2c >/dev/null 2>&1; then
    aria2c -x16 -s16 -k1M --continue=true --file-allocation=none \
      ${HF_TOKEN:+--header="Authorization: Bearer $HF_TOKEN"} \
      -d "$(dirname "$out")" -o "$(basename "$out")" "$url" && return 0
    echo "aria2c ล้ม — ถอยไป curl"
  fi
  curl -fL --retry 5 -C - \
    ${HF_TOKEN:+-H "Authorization: Bearer $HF_TOKEN"} \
    -o "$out" "$url"
}

verify_files() {
  local i path actual_size actual_sha
  for i in "${!MODEL_FILES[@]}"; do
    path="${MODEL_DIR}/${MODEL_FILES[$i]}"
    [[ -f "$path" ]] || die "ยังไม่ได้ download (ไม่พบ $path) — รัน: $0 download"

    if [[ -n "${EXPECTED_SIZES[$i]}" ]]; then
      actual_size="$(stat -c %s "$path" 2>/dev/null || stat -f %z "$path")"
      [[ "$actual_size" == "${EXPECTED_SIZES[$i]}" ]] ||
        die "${MODEL_FILES[$i]}: ขนาดไม่ตรง (ได้ ${actual_size} ต้องการ ${EXPECTED_SIZES[$i]} — download ไม่ครบ?)"
    fi

    if [[ -n "${EXPECTED_SHAS[$i]}" ]]; then
      need sha256sum
      actual_sha="$(sha256sum "$path" | awk '{print $1}')"
      [[ "$actual_sha" == "${EXPECTED_SHAS[$i]}" ]] ||
        die "${MODEL_FILES[$i]}: SHA-256 ไม่ตรง (ได้ ${actual_sha})"
    fi
  done

  local magic
  magic="$(head -c 4 "${MODEL_DIR}/${MODEL_FILE}")"
  [[ "$magic" == "GGUF" ]] || die "ไฟล์แรกไม่ใช่ GGUF (magic: ${magic})"
  echo "verify-files: OK (${#MODEL_FILES[@]} ไฟล์ใน ${MODEL_DIR})"
}

find_cuda_toolkit() {
  # DGX OS ลง CUDA ไว้ที่ /usr/local/cuda แต่ไม่ได้ใส่ใน PATH ของ shell ที่ไม่ใช่ login
  # (เช่นที่ hub เรียกผ่าน SSH) `command -v nvcc` จึงไม่เจอทั้งที่ toolkit อยู่ครบ
  # แล้วเราไปเตือนว่า "ไม่พบ CUDA" ก่อนจะไป build ล้มอีกทีตอน cmake — ทั้งที่แค่ต้องหาให้เจอ
  command -v nvcc >/dev/null 2>&1 && return 0
  local dir
  for dir in /usr/local/cuda/bin /usr/local/cuda-*/bin; do
    if [[ -x "${dir}/nvcc" ]]; then
      export PATH="${dir}:${PATH}"
      echo "พบ CUDA toolkit ที่ ${dir} — เพิ่มเข้า PATH ให้แล้ว"
      return 0
    fi
  done
  return 1
}

install_build_dependencies() {
  # ติดตั้ง build deps ให้อัตโนมัติ — ผู้ใช้ไม่ต้องรู้ล่วงหน้าว่าต้องลงอะไร
  #
  # ninja ไม่อยู่ในลิสต์นี้: cmake ถอยไปใช้ Unix Makefiles ได้เองเมื่อไม่มี ninja
  # การใส่มันไว้ทำให้เครื่องที่มีของครบทุกอย่างแล้วยังต้องไปขอ sudo เพื่อลง generator
  # ที่ไม่ได้จำเป็น แล้วตายทันทีบนเครื่องที่ sudo ขอรหัส (ซึ่งคือค่าปกติของ Ubuntu)
  # — เจอจริงบน msi-4 2026-08-15: ขาดแค่ ninja ทั้งที่ build ได้อยู่แล้ว
  local missing=()
  command -v git   >/dev/null 2>&1 || missing+=(git)
  command -v cmake >/dev/null 2>&1 || missing+=(cmake)
  command -v gcc   >/dev/null 2>&1 || missing+=(build-essential)
  command -v curl  >/dev/null 2>&1 || missing+=(curl)

  if [[ ${#missing[@]} -gt 0 ]]; then
    if ! command -v apt-get >/dev/null 2>&1; then
      die "ขาด dependencies: ${missing[*]} — ระบบไม่มี apt-get ต้องติดตั้งเอง"
    fi
    echo "ติดตั้ง build dependencies ที่ขาด: ${missing[*]}"
    # -n = ไม่ขอรหัสผ่าน · ถ้าเครื่องนี้ต้องใส่รหัส บอกคำสั่งที่ต้องรันไปตรง ๆ
    # ดีกว่าปล่อยให้ sudo ตายพร้อมข้อความ "a terminal is required" ที่ไม่ได้บอกว่าทำอะไรต่อ
    if ! sudo -n true 2>/dev/null; then
      die "ต้องติดตั้ง ${missing[*]} แต่ sudo บนเครื่องนี้ขอรหัสผ่าน — รันคำสั่งนี้เองก่อน:
  sudo apt-get update -y && sudo apt-get install -y ${missing[*]}"
    fi
    sudo apt-get update -y
    sudo apt-get install -y "${missing[@]}"
  fi

  find_cuda_toolkit ||
    echo "คำเตือน: ไม่พบ nvcc (CUDA Toolkit) — ถ้า build ล้มเหลว ติดตั้ง CUDA Toolkit ก่อน (DGX OS มีมาให้แล้ว)"
}

prepare_runtime() {
  # build llama.cpp จาก source — จำเป็นบน DGX Spark (ARM64/SM121 ไม่มี image ทางการ)
  install_build_dependencies
  need git; need cmake; need nvidia-smi
  mkdir -p "$(dirname "$LLAMA_CPP_DIR")" "$RUN_DIR"

  if [[ ! -d "${LLAMA_CPP_DIR}/.git" ]]; then
    echo "clone llama.cpp → ${LLAMA_CPP_DIR}"
    git clone "$LLAMA_CPP_REPO" "$LLAMA_CPP_DIR"
  fi

  local commit
  if [[ -f "$RUNTIME_LOCK" ]]; then
    commit="$(cat "$RUNTIME_LOCK")"
    echo "ใช้ commit ที่ lock ไว้: ${commit}"
  else
    git -C "$LLAMA_CPP_DIR" fetch --all --quiet
    git -C "$LLAMA_CPP_DIR" checkout --quiet "$LLAMA_CPP_REF"
    if [[ "$LLAMA_CPP_REF" == "master" ]]; then
      git -C "$LLAMA_CPP_DIR" pull --quiet
    fi
    commit="$(git -C "$LLAMA_CPP_DIR" rev-parse HEAD)"
  fi
  git -C "$LLAMA_CPP_DIR" checkout --quiet "$commit"

  echo "build (CUDA arch: ${CUDA_ARCHITECTURES}) — ใช้เวลาหลายนาที..."
  cmake -S "$LLAMA_CPP_DIR" -B "${LLAMA_CPP_DIR}/build" \
    -DGGML_CUDA=ON \
    -DGGML_NATIVE=ON \
    -DCMAKE_BUILD_TYPE=Release \
    -DCMAKE_CUDA_ARCHITECTURES="$CUDA_ARCHITECTURES"
  cmake --build "${LLAMA_CPP_DIR}/build" --config Release --target llama-server -j "$(nproc)"

  [[ -x "$LLAMA_SERVER" ]] || die "build ไม่สำเร็จ — ไม่พบ ${LLAMA_SERVER}"
  printf '%s\n' "$commit" > "$RUNTIME_LOCK"
  echo "runtime พร้อม (pinned: ${commit})"
  "$LLAMA_SERVER" --version 2>&1 || true
}

check_gpu() {
  if [[ "$RUNTIME_MODE" == "native" ]]; then
    need nvidia-smi
    nvidia-smi -L
  else
    need docker
    local out
    out="$(docker run --rm --gpus all --entrypoint nvidia-smi "$LLAMACPP_IMAGE" -L 2>&1)" ||
      die "GPU ใน container ใช้ไม่ได้: $out"
    echo "$out"
  fi
}

server_args() {
  SERVER_ARGS=(
    -m "${MODEL_MOUNT_DIR}/${MODEL_FILE}"
    --alias "$SERVED_MODEL_NAME"
    --ctx-size "$CTX_SIZE"
    --n-gpu-layers "$N_GPU_LAYERS"
    --parallel "$PARALLEL_SEQS"
    --host "$API_HOST"
    --port "$API_PORT"
  )
  if [[ -n "$API_KEY" ]]; then SERVER_ARGS+=(--api-key "$API_KEY"); fi



}

write_meta() {
  # ลงทะเบียนกับ lmds fleet (~/.lmds/run) — ให้ lmds ps/stop/logs เห็นเซิร์ฟเวอร์ตัวนี้
  mkdir -p "$RUN_DIR"
  local script_path
  script_path="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/$(basename "${BASH_SOURCE[0]}")"
  cat > "${RUN_DIR}/server.meta" <<EOF
slug=huihui-qwen3-coder-30b-a3b-instruct-abliterated-gguf
model=${SERVED_MODEL_NAME}
model_id=${MODEL_ID}
engine=llamacpp
mode=${RUNTIME_MODE}
port=${API_PORT}
container=${CONTAINER_NAME}
pid_file=${PID_FILE}
controller=${script_path}
started_at=$(date +%Y-%m-%dT%H:%M:%S)
EOF
}

ensure_image() {
  # ดึง image ให้เห็นความคืบหน้า *ก่อน* จะเอาไปใช้ที่อื่น
  #
  # เดิม image ที่ยังไม่มีถูกดึงเงียบ ๆ ระหว่าง `docker run` ที่ผลถูกเก็บเข้าตัวแปร
  # (`out="$(docker run ... 2>&1)"`) — progress bar ของ docker จึงหายเข้าไปในตัวแปร
  # ผู้ใช้เห็นแค่บรรทัดสุดท้ายค้างอยู่หลายสิบนาที แยกไม่ออกว่ากำลังโหลดหรือค้างไปแล้ว
  # (image พวกนี้ 20-30 GB · เจอจริงกับ avarok/dgx-vllm-nvfp4-kernel)
  local image="$1"
  docker image inspect "$image" >/dev/null 2>&1 && return 0
  echo "ดึง image ${image} (ยังไม่มีในเครื่อง — ขนาดหลาย GB ใช้เวลาสักครู่)…"
  docker pull "$image" || die "ดึง image ${image} ไม่สำเร็จ"
}

check_port_free() {
  # ไม่เลือก port ให้ — ผู้ใช้เป็นคนกำหนด (เครื่องเดียวรัน llama.cpp ได้หลายตัว)
  # แต่ห้าม start ทับของคนอื่นเด็ดขาด เพราะ wait_health ยิง /health ที่ port นี้
  # แล้ว "โมเดลตัวที่ยึด port อยู่" จะตอบ 200 ให้ → รายงานว่า start สำเร็จ
  # ทั้งที่ตัวเราไม่ได้ขึ้นเลย แล้วทุกคนก็คุยกับโมเดลผิดตัวโดยไม่รู้
  #
  # เคสจริง 2026-08-13 บน dgx-veerasiam: gemma กับ qwen ใช้ default port เดียวกัน
  #
  # ตรวจด้วย /dev/tcp ของ bash เอง ไม่เรียก awk/lsof — เวอร์ชันแรกของฟังก์ชันนี้ใช้
  # awk แล้ว $4 กับ $NF ของ awk ไปชนกับ positional parameter ของ bash เข้า
  # set -u จึงตายที่ "unbound variable" ตอนผู้ใช้กด start (bash -n ไม่จับให้ เพราะ
  # เป็นเรื่องตอนรัน ไม่ใช่ syntax)
  local holder=""
  if ! (exec 3<>"/dev/tcp/127.0.0.1/${API_PORT}") 2>/dev/null; then
    return 0
  fi
  # มีคนฟังอยู่จริง — พยายามบอกว่าใคร ถ้าบอกไม่ได้ก็ยังต้องหยุดอยู่ดี
  holder="$(ss -ltnp 2>/dev/null | grep ":${API_PORT} " || true)"
  holder="$(printf "%s" "$holder" | head -1)"
  die "port ${API_PORT} ถูกใช้อยู่แล้ว${holder:+ — ${holder}}
     เครื่องนี้รัน llama.cpp ได้หลายตัว แต่ต้องคนละ port
     เลือก port อื่น:  $0 start --port <PORT>
     หรือดูว่าใครถืออยู่: ss -ltnp | grep :${API_PORT}"
}

start() {
  verify_files
  mkdir -p "$RUN_DIR"
  check_port_free

  if [[ "$RUNTIME_MODE" == "native" ]]; then
    [[ -x "$LLAMA_SERVER" ]] || die "ยังไม่มี llama-server — รัน: $0 prepare-runtime"
    if [[ -f "$PID_FILE" ]] && kill -0 "$(cat "$PID_FILE")" 2>/dev/null; then
      die "เซิร์ฟเวอร์รันอยู่แล้ว (PID $(cat "$PID_FILE")) — รัน: $0 stop ก่อน"
    fi
    check_gpu >/dev/null
    MODEL_MOUNT_DIR="$MODEL_DIR"
    server_args
    nohup "$LLAMA_SERVER" "${SERVER_ARGS[@]}" >> "$LOG_FILE" 2>&1 &
    echo "$!" > "$PID_FILE"
  else
    need docker
    ensure_image "${LLAMACPP_IMAGE}"
    # ซากจากรอบก่อนไม่ใช่ของที่กำลังทำงาน — เก็บกวาดเองแล้วไปต่อ (ดูเหตุผลใน vllm controller)
    local running_now
    running_now="$(docker ps --filter "name=^${CONTAINER_NAME}$" --format '{{.Names}}' 2>/dev/null || true)"
    [[ -z "$running_now" ]] || die "container ${CONTAINER_NAME} กำลังรันอยู่ — รัน: $0 stop ก่อน"
    local leftover
    leftover="$(docker ps -a --filter "name=^${CONTAINER_NAME}$" --format '{{.Names}}' 2>/dev/null || true)"
    if [[ -n "$leftover" ]]; then
      echo "เก็บซาก container จากรอบก่อน (${CONTAINER_NAME}) แล้วเริ่มใหม่"
      docker rm -f "${CONTAINER_NAME}" >/dev/null 2>&1 || true
    fi
    check_gpu >/dev/null
    MODEL_MOUNT_DIR="/models"
    server_args
    docker run -d --name "$CONTAINER_NAME" \
      --network host --gpus all \
      -v "${MODEL_DIR}:/models:ro" \
      "$LLAMACPP_IMAGE" \
      "${SERVER_ARGS[@]}"
  fi

  write_meta
  wait_health
  echo "started: $(detect_advertise_ip):${API_PORT} (${SERVED_MODEL_NAME})"
  warn_open_endpoint
  network_info
}

warn_open_endpoint() {
  # bind 0.0.0.0 + ไม่มี key = ใครก็ตามในวง network ยิง API ได้โดยไม่ต้องยืนยันตัวตน
  [[ "$API_HOST" == "0.0.0.0" && -z "$API_KEY" ]] || return 0
  echo "คำเตือน: เปิดให้ทั้งวง network เข้าถึงได้โดยไม่มี API key" >&2
  echo "         ใช้เฉพาะในเครื่อง: $0 restart --bind 127.0.0.1" >&2
  echo "         หรือบังคับ token:  API_KEY=\$(openssl rand -hex 24) $0 restart" >&2
}

server_alive() {
  if [[ "$RUNTIME_MODE" == "native" ]]; then
    [[ -f "$PID_FILE" ]] && kill -0 "$(cat "$PID_FILE")" 2>/dev/null
  else
    local running
    running="$(docker ps --filter "name=^${CONTAINER_NAME}$" --format '{{.Names}}' 2>/dev/null || true)"
    [[ -n "$running" ]]
  fi
}

wait_health() {
  local waited=0
  echo "รอ /health (สูงสุด ${HEALTH_TIMEOUT}s — โมเดลใหญ่โหลดหลายนาที)..."
  until curl -fsS "http://127.0.0.1:${API_PORT}/health" >/dev/null 2>&1; do
    server_alive || die "เซิร์ฟเวอร์หยุดก่อน health ผ่าน — ดู: $0 logs"
    if (( waited >= HEALTH_TIMEOUT )); then
      echo "ยังไม่ health ภายใน ${HEALTH_TIMEOUT}s — เซิร์ฟเวอร์ยังโหลดต่ออยู่ ไม่ได้ถูกหยุด" >&2
      echo "รอต่อ:      $0 wait-health" >&2
      echo "ดูคืบหน้า:   $0 logs 100" >&2
      echo "รอบหน้ารอนานขึ้น: HEALTH_TIMEOUT=3600 $0 start" >&2
      exit 1
    fi
    sleep 5
    waited=$(( waited + 5 ))
  done
}

stop() {
  # รายงานตามความจริง — เดิมพิมพ์ "stopped" เสมอแม้ไม่มีอะไรรันอยู่เลย
  # ซึ่งอันตรายเงียบ ๆ: ถ้า PID/ชื่อ container เพี้ยน ผู้ใช้จะเชื่อว่าหยุดแล้วทั้งที่ยังรันอยู่
  local stopped=0
  if [[ "$RUNTIME_MODE" == "native" ]]; then
    if [[ -f "$PID_FILE" ]] && kill "$(cat "$PID_FILE")" 2>/dev/null; then
      stopped=1
    fi
    rm -f "$PID_FILE"
  elif docker rm -f "$CONTAINER_NAME" >/dev/null 2>&1; then
    stopped=1
  fi

  if (( stopped )); then
    echo "stopped ${SERVED_MODEL_NAME}"
  else
    echo "ไม่มีอะไรให้หยุด (${SERVED_MODEL_NAME} ไม่ได้รันอยู่)"
  fi
}

status() {
  if [[ "$RUNTIME_MODE" == "native" ]]; then
    if server_alive; then echo "process: running (PID $(cat "$PID_FILE"))"; else echo "process: stopped"; fi
  else
    docker ps -a --filter "name=^${CONTAINER_NAME}$"
  fi
  if curl -fsS "http://127.0.0.1:${API_PORT}/health" >/dev/null 2>&1; then
    echo "API: healthy"
  else
    echo "API: not responding"
  fi
}

logs() {
  if [[ "$RUNTIME_MODE" == "native" ]]; then
    tail -n "${1:-300}" "$LOG_FILE"
  else
    docker logs --tail "${1:-300}" "$CONTAINER_NAME"
  fi
}

client_config() {
  # llama.cpp แบ่ง --ctx-size เท่า ๆ กันให้ทุก slot (--parallel) — budget ต้องคิดจาก context ต่อ slot จริง
  local slot_context input_budget
  slot_context=$(( CTX_SIZE / PARALLEL_SEQS ))
  if [[ "$CLIENT_INPUT" == "auto" ]]; then
    input_budget=$(( slot_context - CLIENT_OUTPUT - TEMPLATE_OVERHEAD_TOKENS ))
  else
    input_budget="$CLIENT_INPUT"
  fi
  (( input_budget > 0 )) ||
    die "context ต่อ slot เล็กเกิน (${slot_context} = ${CTX_SIZE}/${PARALLEL_SEQS}) — เพิ่ม --context หรือลด PARALLEL_SEQS"
  cat <<EOF
{
  "base_url": "http://$(detect_advertise_ip):${API_PORT}/v1",
  "model": "${SERVED_MODEL_NAME}",
  "api_key": "${API_KEY:-not-required}",
  "max_input_tokens": ${input_budget},
  "max_output_tokens": ${CLIENT_OUTPUT},
  "server_context_total": ${CTX_SIZE},
  "context_per_slot": ${slot_context},
  "parallel_slots": ${PARALLEL_SEQS}
}
EOF
}



test_text() {
  assert_our_server
  # 512 ไม่ใช่ 64: โมเดลสาย reasoning (gemma-4, Qwen3 thinking ฯลฯ) ใช้ budget ไปกับ
  # reasoning_content ก่อน ถ้าให้น้อยจะได้ content ว่างเปล่า + finish_reason "length"
  # ซึ่งดูเหมือนโมเดลพัง ทั้งที่จริงแค่พื้นที่ตอบไม่พอ
  local response
  response="$(curl -fsS "http://127.0.0.1:${API_PORT}/v1/chat/completions" \
    ${API_KEY:+-H "Authorization: Bearer $API_KEY"} \
    -H "Content-Type: application/json" \
    -d "{
      \"model\": \"${SERVED_MODEL_NAME}\",
      \"messages\": [{\"role\": \"user\", \"content\": \"ตอบสั้น ๆ: 2+2 เท่ากับเท่าไร\"}],
      \"max_tokens\": 512
    }")" || die "เรียก /v1/chat/completions ไม่สำเร็จ — ดู log: $0 logs 200"

  echo "$response"
  echo ""

  # สรุปให้อ่านออกโดยไม่ต้องเพ่ง JSON — และแยก "ตอบว่าง" ออกจาก "ตอบได้"
  if command -v python3 >/dev/null 2>&1; then
    printf '%s' "$response" | python3 -c '
import json, sys
try:
    msg = json.load(sys.stdin)["choices"][0]["message"]
except (ValueError, KeyError, IndexError):
    sys.exit(0)
content = (msg.get("content") or "").strip()
if content:
    print(f"test-text: OK — {content[:200]}")
elif (msg.get("reasoning_content") or "").strip():
    print("test-text: โมเดลตอบแต่ยังคิดไม่จบใน 512 tokens (reasoning model)")
    print("           ไม่ใช่ความผิดพลาด — ลองถามคำถามที่ยาวขึ้นผ่าน /v1/chat/completions ได้เลย")
else:
    print("test-text: เซิร์ฟเวอร์ตอบกลับแต่ไม่มีข้อความ — ดู log: logs 200")
' || true
  fi
}

usage() {
  cat <<EOF
huihui-qwen3-coder-30b-a3b-instruct-abliterated-gguf — llama.cpp controller  (model: ${MODEL_ID})
Runtime mode: ${RUNTIME_MODE}   (override with RUNTIME_MODE=docker|native)

USAGE
  $0 <command> [options]

COMMANDS
  prepare-runtime   Build llama.cpp from source. REQUIRED once in 'native' mode
                    (DGX Spark / ARM64 has no official image). Installs build deps via apt (sudo).
  download          Download every model part (resumable, revision pinned)
  verify-files      Verify all files: exact size + SHA-256 + GGUF magic
  start             Verify GPU + files, then start llama-server and wait for /health
  stop              Stop the server
  restart           stop + start (use this to apply new options)
  status            Process/container state + API health
  logs [N]          Show last N log lines (default 300).  Live tail: lmds logs huihui-qwen3-coder-30b-a3b-instruct-abliterated-gguf -f
  wait-health       Keep waiting for /health (use if start timed out but the model is still loading)
  client-config     Print client settings as JSON (base_url, model name, token budget)
  network-info      Show current bind address and the endpoint advertised to clients
  test-text         Send one chat completion request to verify the model answers


OPTIONS  (can be placed after any command; equals form also works: --port=8001)
  --port N              Port to serve on                          [default: ${API_PORT}]
  --context N           Max context length in tokens              [default: ${CTX_SIZE}]
                        Lower this first if the server runs out of memory.
  --bind ADDR           Address the server listens on             [default: ${API_HOST}]
                        0.0.0.0 = reachable from the whole network
                        127.0.0.1 = this machine only (safest)
  --advertise-ip ADDR   IP printed for clients. Does NOT change what the server binds to.
                        Use when the machine has several NICs or sits behind NAT.
  --interface NAME      Pick the advertised IP from this interface (e.g. eth0) instead of auto-detect
  --client-input N|auto Input token budget written into client-config   [default: ${CLIENT_INPUT}]
  --client-output N     Output token budget written into client-config  [default: ${CLIENT_OUTPUT}]

API TOKEN (authentication)
  There is NO token by default: anyone who can reach ${API_HOST}:${API_PORT} can use the model.
  Set one with the API_KEY environment variable — it is passed to llama-server as --api-key:

    API_KEY=my-secret-token $0 restart          # start the server with authentication on
    API_KEY=\$(openssl rand -hex 24) $0 restart  # or generate a random one

  Clients then send it as a bearer token:

    curl http://<ip>:${API_PORT}/v1/chat/completions \\
      -H "Authorization: Bearer my-secret-token" \\
      -H 'Content-Type: application/json' \\
      -d '{"model":"${SERVED_MODEL_NAME}","messages":[{"role":"user","content":"hi"}]}'

  The token is NOT stored in this script — you must pass API_KEY on every start/restart
  (put it in your shell profile or a systemd drop-in to make it permanent).
  Without a token, prefer:  $0 restart --bind 127.0.0.1

ENVIRONMENT VARIABLES
  API_KEY             Bearer token required from clients        [default: none]
  API_PORT / API_HOST Same as --port / --bind
  CTX_SIZE            Same as --context
  RUNTIME_MODE        docker | native                            [default: ${RUNTIME_MODE}]
  MODEL_DIR           Where GGUF files are stored                [default: ${MODEL_DIR}]
  HF_TOKEN            Hugging Face token, needed for gated repos during 'download'
  N_GPU_LAYERS        Layers offloaded to GPU (fewer = less VRAM, slower)
  HEALTH_TIMEOUT      Seconds to wait for /health on start        [default: ${HEALTH_TIMEOUT}]
  LLAMA_CPP_DIR       llama.cpp source/build dir (native mode)    [default: ${LLAMA_CPP_DIR}]
  CUDA_ARCHITECTURES  CUDA arch used by prepare-runtime           [default: ${CUDA_ARCHITECTURES}]
  RUN_DIR             Runtime state read by 'lmds ps'             [default: ${RUN_DIR}]

EXAMPLES
  $0 start --port 8001 --context 16384        # different port, smaller context
  $0 restart --bind 127.0.0.1                 # lock the endpoint to this machine
  API_KEY=secret123 $0 restart                # require a bearer token
  HF_TOKEN=hf_xxx $0 download                 # gated repository
  MODEL_DIR=/data/models $0 download          # keep weights on another disk (also set it on start)
EOF
}

parse_options "$@"
set -- ${REMAINING_ARGS[@]+"${REMAINING_ARGS[@]}"}


banner() {
  cat <<'ART'

  _     __  __ ____  ____
 | |   |  \/  |  _ \/ ___|
 | |   | |\/| | | | \___ \
 | |___| |  | | |_| |___) |
 |_____|_|  |_|____/|____/
ART
  printf '       =[ LMDS controller · v%s ]\n' "${SCRIPT_VERSION}"
  printf '+ -- --=[ %s ]\n' "${MODEL_LABEL}"
  printf '+ -- --=[ %s · %s ]\n' "${RUNTIME_LABEL}" "${MODEL_FEATURES}"
  printf '+ -- --=[ Designed by neronain · fb.com/neronain.minidev ]\n\n'
}

# สรุปว่า controller นี้เสิร์ฟโมเดลอะไร ที่พอร์ตไหน และตอนนี้ขึ้นหรือยัง
info() {
  banner
  local ip url state
  ip="$(detect_advertise_ip 2>/dev/null || true)"; [[ -n "$ip" ]] || ip="${API_HOST}"
  url="http://${ip}:${API_PORT}/v1"
  state="stopped"
  if curl -fsS -m 2 "http://127.0.0.1:${API_PORT}/health" >/dev/null 2>&1; then
    state="RUNNING"
  fi
  printf '  Model     : %s\n'            "${MODEL_LABEL}"
  printf '  Model ID  : %s\n'            "${MODEL_ID}"
  printf '  Runtime   : %s\n'            "${RUNTIME_LABEL}"
  printf '  Features  : %s\n'            "${MODEL_FEATURES}"
  printf '  Context   : %s tokens\n'     "${MAX_MODEL_LEN:-${CTX_SIZE:-n/a}}"
  printf '  API (v1)  : %s\n'            "${url}"
  printf '  State     : %s  (port %s)\n\n' "${state}" "${API_PORT}"
}

case "${1:-help}" in
  prepare-runtime) prepare_runtime ;;
  download)     download ;;
  verify-files) verify_files ;;
  start)        start ;;
  stop)         stop ;;
  restart)      stop; start ;;
  status)       status ;;
  logs)         logs "${2:-300}" ;;
  client-config) client_config ;;
  info|banner) info ;;
  network-info) network_info ;;
  test-text)    test_text ;;

  wait-health)  wait_health ;;
  *)            usage ;;
esac
